### PR TITLE
Use same-origin for credentials mode (cors mode does not exist)

### PR DESCRIPTION
**Pull request by tomgilligan**
We were giving `'cors'` as the `credential` parameter when fetching the docs JSON.  The only possible values for the `credential` parameter are `'omit'`, `'include'` and `'same-origin'`.  Chrome silently accepts an unknown `credential` value and makes the request.  Other browsers throw an exception and these browsers would fail to load the JSON because of it.

### CODE REVIEW

**Comment by twe4ked** [comment]
Bit of context would be nice. I assume this fixes the Safari bug?

**Comment by tomgilligan** [comment]
Yep, soz should have added that to the description

**Comment by tomgilligan** [comment]
@twe4ked  sorry i think i should have made this PR on your repo and updated this repo from that one. next time.

**Comment by twe4ked** [comment]
No worries, I'll pull the change across in my own time. Thanks.

**Pull request merged**
